"""Initial migration - modelos alineados con schemas

Revision ID: 48b949d57135
Revises: 
Create Date: 2025-10-18 06:10:27.409399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48b949d57135'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conceptos_tic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_conceptos_tic_id'), 'conceptos_tic', ['id'], unique=False)
    op.create_table('licitaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_licitacion', sa.String(length=255), nullable=False),
    sa.Column('titulo', sa.Text(), nullable=False),
    sa.Column('expediente', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('resumen', sa.Text(), nullable=True),
    sa.Column('organo_contratacion', sa.String(length=500), nullable=True),
    sa.Column('nif_organo', sa.String(length=20), nullable=True),
    sa.Column('web_organo', sa.String(length=500), nullable=True),
    sa.Column('email_organo', sa.String(length=255), nullable=True),
    sa.Column('telefono_organo', sa.String(length=50), nullable=True),
    sa.Column('ciudad_organo', sa.String(length=100), nullable=True),
    sa.Column('codigo_postal_organo', sa.String(length=10), nullable=True),
    sa.Column('tipo_contrato', sa.String(length=100), nullable=True),
    sa.Column('tipo_contrato_codigo', sa.String(length=10), nullable=True),
    sa.Column('presupuesto_base', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('valor_estimado', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('lugar_ejecucion', sa.String(length=500), nullable=True),
    sa.Column('codigo_nuts', sa.String(length=20), nullable=True),
    sa.Column('codigos_cpv', sa.JSON(), nullable=True),
    sa.Column('duracion', sa.Integer(), nullable=True),
    sa.Column('duracion_unidad', sa.String(length=20), nullable=True),
    sa.Column('procedimiento_codigo', sa.String(length=10), nullable=True),
    sa.Column('financiacion_ue', sa.String(length=10), nullable=True),
    sa.Column('fecha_publicacion', sa.TIMESTAMP(), nullable=True),
    sa.Column('fecha_vencimiento', sa.TIMESTAMP(), nullable=True),
    sa.Column('fecha_limite_presentacion', sa.TIMESTAMP(), nullable=True),
    sa.Column('hora_limite_presentacion', sa.String(length=10), nullable=True),
    sa.Column('resultado_codigo', sa.String(length=10), nullable=True),
    sa.Column('fecha_adjudicacion', sa.TIMESTAMP(), nullable=True),
    sa.Column('adjudicatario', sa.String(length=500), nullable=True),
    sa.Column('nif_adjudicatario', sa.String(length=20), nullable=True),
    sa.Column('importe_adjudicacion', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('conceptos_tic', sa.JSON(), nullable=True),
    sa.Column('stack_tecnologico', sa.JSON(), nullable=True),
    sa.Column('resumen_tecnico', sa.JSON(), nullable=True),
    sa.Column('analizado_ia', sa.Boolean(), nullable=True),
    sa.Column('fecha_analisis_ia', sa.TIMESTAMP(), nullable=True),
    sa.Column('link', sa.Text(), nullable=True),
    sa.Column('fuente', sa.String(length=100), nullable=True),
    sa.Column('hash_contenido', sa.String(length=64), nullable=True),
    sa.Column('fecha_actualizacion', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_licitacion')
    )
    op.create_index(op.f('ix_licitaciones_estado'), 'licitaciones', ['estado'], unique=False)
    op.create_index(op.f('ix_licitaciones_fecha_publicacion'), 'licitaciones', ['fecha_publicacion'], unique=False)
    op.create_index(op.f('ix_licitaciones_fecha_vencimiento'), 'licitaciones', ['fecha_vencimiento'], unique=False)
    op.create_index(op.f('ix_licitaciones_hash_contenido'), 'licitaciones', ['hash_contenido'], unique=True)
    op.create_index(op.f('ix_licitaciones_id'), 'licitaciones', ['id'], unique=False)
    op.create_index(op.f('ix_licitaciones_presupuesto_base'), 'licitaciones', ['presupuesto_base'], unique=False)
    op.create_table('organismos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=500), nullable=False),
    sa.Column('nif', sa.String(length=20), nullable=True),
    sa.Column('tipo', sa.String(length=100), nullable=True),
    sa.Column('web', sa.String(length=500), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('ciudad', sa.String(length=100), nullable=True),
    sa.Column('codigo_postal', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nif')
    )
    op.create_index(op.f('ix_organismos_id'), 'organismos', ['id'], unique=False)
    op.create_table('scraping_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fuente', sa.String(length=100), nullable=False),
    sa.Column('fecha_inicio', sa.TIMESTAMP(), nullable=False),
    sa.Column('fecha_fin', sa.TIMESTAMP(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('licitaciones_nuevas', sa.Integer(), nullable=True),
    sa.Column('licitaciones_actualizadas', sa.Integer(), nullable=True),
    sa.Column('errores', sa.Integer(), nullable=True),
    sa.Column('mensaje_error', sa.Text(), nullable=True),
    sa.Column('metadata_extra', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scraping_logs_created_at'), 'scraping_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_scraping_logs_fuente'), 'scraping_logs', ['fuente'], unique=False)
    op.create_index(op.f('ix_scraping_logs_id'), 'scraping_logs', ['id'], unique=False)
    op.create_table('tecnologias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_tecnologias_id'), 'tecnologias', ['id'], unique=False)
    op.create_table('adjudicaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('licitacion_id', sa.Integer(), nullable=False),
    sa.Column('adjudicatario', sa.String(length=500), nullable=False),
    sa.Column('nif_adjudicatario', sa.String(length=20), nullable=True),
    sa.Column('importe', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('fecha_adjudicacion', sa.TIMESTAMP(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['licitacion_id'], ['licitaciones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adjudicaciones_id'), 'adjudicaciones', ['id'], unique=False)
    op.create_table('documentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('licitacion_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=500), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('url_descarga', sa.Text(), nullable=True),
    sa.Column('url_almacenamiento', sa.Text(), nullable=True),
    sa.Column('tamano_bytes', sa.Integer(), nullable=True),
    sa.Column('hash_archivo', sa.String(length=64), nullable=True),
    sa.Column('procesado', sa.Boolean(), nullable=True),
    sa.Column('texto_extraido', sa.Text(), nullable=True),
    sa.Column('metadata_extra', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['licitacion_id'], ['licitaciones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documentos_id'), 'documentos', ['id'], unique=False)
    op.create_index(op.f('ix_documentos_licitacion_id'), 'documentos', ['licitacion_id'], unique=False)
    op.create_table('licitaciones_conceptos',
    sa.Column('licitacion_id', sa.Integer(), nullable=False),
    sa.Column('concepto_id', sa.Integer(), nullable=False),
    sa.Column('relevancia', sa.String(length=20), nullable=True),
    sa.Column('confianza', sa.DECIMAL(precision=3, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['concepto_id'], ['conceptos_tic.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['licitacion_id'], ['licitaciones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('licitacion_id', 'concepto_id')
    )
    op.create_table('licitaciones_tecnologias',
    sa.Column('licitacion_id', sa.Integer(), nullable=False),
    sa.Column('tecnologia_id', sa.Integer(), nullable=False),
    sa.Column('confianza', sa.DECIMAL(precision=3, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['licitacion_id'], ['licitaciones.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tecnologia_id'], ['tecnologias.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('licitacion_id', 'tecnologia_id')
    )
    op.create_table('resumenes_ia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('licitacion_id', sa.Integer(), nullable=False),
    sa.Column('resumen_ejecutivo', sa.Text(), nullable=True),
    sa.Column('requisitos_tecnicos', sa.JSON(), nullable=True),
    sa.Column('stack_recomendado', sa.JSON(), nullable=True),
    sa.Column('nivel_complejidad', sa.String(length=20), nullable=True),
    sa.Column('puntuacion_relevancia', sa.DECIMAL(precision=3, scale=2), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['licitacion_id'], ['licitaciones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('licitacion_id')
    )
    op.create_index(op.f('ix_resumenes_ia_id'), 'resumenes_ia', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resumenes_ia_id'), table_name='resumenes_ia')
    op.drop_table('resumenes_ia')
    op.drop_table('licitaciones_tecnologias')
    op.drop_table('licitaciones_conceptos')
    op.drop_index(op.f('ix_documentos_licitacion_id'), table_name='documentos')
    op.drop_index(op.f('ix_documentos_id'), table_name='documentos')
    op.drop_table('documentos')
    op.drop_index(op.f('ix_adjudicaciones_id'), table_name='adjudicaciones')
    op.drop_table('adjudicaciones')
    op.drop_index(op.f('ix_tecnologias_id'), table_name='tecnologias')
    op.drop_table('tecnologias')
    op.drop_index(op.f('ix_scraping_logs_id'), table_name='scraping_logs')
    op.drop_index(op.f('ix_scraping_logs_fuente'), table_name='scraping_logs')
    op.drop_index(op.f('ix_scraping_logs_created_at'), table_name='scraping_logs')
    op.drop_table('scraping_logs')
    op.drop_index(op.f('ix_organismos_id'), table_name='organismos')
    op.drop_table('organismos')
    op.drop_index(op.f('ix_licitaciones_presupuesto_base'), table_name='licitaciones')
    op.drop_index(op.f('ix_licitaciones_id'), table_name='licitaciones')
    op.drop_index(op.f('ix_licitaciones_hash_contenido'), table_name='licitaciones')
    op.drop_index(op.f('ix_licitaciones_fecha_vencimiento'), table_name='licitaciones')
    op.drop_index(op.f('ix_licitaciones_fecha_publicacion'), table_name='licitaciones')
    op.drop_index(op.f('ix_licitaciones_estado'), table_name='licitaciones')
    op.drop_table('licitaciones')
    op.drop_index(op.f('ix_conceptos_tic_id'), table_name='conceptos_tic')
    op.drop_table('conceptos_tic')
    # ### end Alembic commands ###

